name: Build and deploy

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - name: Install NPM packages
      run: npm ci

    - name: Build project
      run: npm run build
      env:
        REACT_APP_URL_LAMBDA: ${{ secrets.REACT_APP_URL_LAMBDA }}
        REACT_APP_SHOW_COMMUNITY_VIEW: ${{ secrets.REACT_APP_SHOW_COMMUNITY_VIEW }}


    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PAGES_TOKEN }}
        publish_dir: ./build
